app('address_width 32', echo=True)
app('line_size_width 4', echo=True)
app('create Apartado A', echo=True)
app('name Memory', echo=True)
app('memory', echo=True)

app('name CacheL2', echo=True)
app('set_width 14', echo=True)
app('way_width 2', echo=True)
app('policy FIFO', echo=True)
app('write_back True', echo=True)
app('write_allocate True', echo=True)
app('prefetch 0', echo=True)
app('cache', echo=True)
app('cost_access 0', echo=True)
app('cost_hit 1', echo=True)
app('cost_miss 200', echo=True)
app('cost_through 200', echo=True)
app('reset_costs', echo=True)

app('name CacheL1', echo=True)
app('set_width 4', echo=True)
app('way_width 0', echo=True)
app('policy FIFO', echo=True)
app('write_back True', echo=True)
app('write_allocate False', echo=True)
app('prefetch 0', echo=True)
app('cache', echo=True)
app('cost_access 1', echo=True)
app('cost_hit 0', echo=True)
app('cost_miss 15', echo=True)
app('cost_through 50', echo=True)
app('reset_costs', echo=True)
for i in range(128):
    if (i > 7 and i < 64):
        app('read ' + str(8*i), echo=True)
        app('write ' + str(8*i + 4), echo=True)
    else:
        app('read ' + str(8*i), echo=True)
        app('read ' + str(8*i+4), echo=True)
app('show_state stats', echo=True)
app('show_costs', echo=True)