app('virtual_address_width 20', echo=False)
app('address_width 17', echo=False)
app('line_size_width 15', echo=False)
app('create Ej virt 1', echo=False)
app('policy LRU', echo=False)
app('name Physical', echo=False)
app('set_width 2', echo=False)
app('way_width 0', echo=False)
app('cache', echo=False)
app('name Cache', echo=False)
app('line_size_width 8', echo=False)
app('set_width 2', echo=False)
app('way_width 0', echo=False)
app('cache', echo=False)
app('line_size_width 15', echo=False)
app('name Virtual', echo=False)
app('virtual', echo=False)

app('read 0x10000', echo=False)
app('read 0x51D00', echo=False)
app('read 0x51E00', echo=False)
app('read 0x51F00', echo=False)
app('read 0x60000', echo=False)
app('read 0xF4000', echo=False)

app('show_state', echo=False)
app('reset_stats', echo=False)

app('read 0xF40F5', echo=True)
app('read 0x66000', echo=True)
app('read 0x40040', echo=True)
app('read 0x51D04', echo=True)
app('show_state', echo=True)